### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by ctf0** [tbremer/px-rem-tooltip-sublime#1]
maybe u can merge https://packagecontrol.io/packages/REM%20PX along with ur package ?

**Comment by tbremer** [comment]
Hm… I'll have to think on this one. Seems to be that installing both would keep this package as light weight as possible.

**Comment by ctf0** [comment]
yea but not everyone knows about both packages, also having all in one plugin would be a complete solution for anyone interested in converting from px to rem

**Comment by ctf0** [comment]
another idea would be clicking the tooltip to change the current px to rem on the fly.
