### ISSUE TITLE
Tooltip are displayed always?

### ISSUE THREAD

**Issue by PixelT** [tbremer/px-rem-tooltip-sublime#3]
IMO tooltip should be display only when the cursor is over the length value

![](http://i.imgur.com/9rPsBqp.png)

**Comment by tbremer** [comment]
I can't seem to replicate this one, is it another package you have installed?

Perhaps you could send me a few items:
- list of packages you have installed
- colorscheme & theme (perhaps my colors are such that I don't see it)
- a code snippet (with Syntax) where this occurs.

Thanks!

FWIW, this is what I am seeing replicating as best I can…
![image](https://cloud.githubusercontent.com/assets/2998575/15727012/a86408c6-2819-11e6-860e-48cfe808d443.png)

**Comment by PixelT** [comment]
I have a lot of packages :P

> "installed_packages":
>     [
>         "AlignTab",
>         "All Autocomplete",
>         "ApacheConf.tmLanguage",
>         "Auto Semi-Colon",
>         "AutoFileName",
>         "AutoSetSyntax",
>         "Boxy Theme",
>         "BracketHighlighter",
>         "BufferScroll",
>         "Chain of Command",
>         "Clickable URLs",
>         "Color Highlighter",
>         "ColorHelper",
>         "Console Wrap for js",
>         "CSS Extended Completions",
>         "CSScomb",
>         "EasyDiff",
>         "Emmet",
>         "Exclude Paths",
>         "FileDiffs",
>         "FindResultsApplyChanges",
>         "Fix Mac Path",
>         "Git",
>         "GitGutter-Edge",
>         "Goto-CSS-Declaration",
>         "Gulp",
>         "Gutter Themes for SL",
>         "HTML Nest Comments",
>         "HTML-CSS-JS Prettify",
>         "HTML5",
>         "HTMLAttributes",
>         "jQuery",
>         "LESS",
>         "List stylesheet variables",
>         "Local History",
>         "LockTab",
>         "Monokai Extended",
>         "More Layouts",
>         "Open-Include",
>         "Package Control",
>         "Package Syncing",
>         "PackageResourceViewer",
>         "PlainNotes",
>         "PlainTasks",
>         "PxRemTooltip",
>         "QuickThemes",
>         "Random Everything",
>         "Sass",
>         "SASS Snippets",
>         "SCSS",
>         "SideBarEnhancements",
>         "SideBarFolders",
>         "SideBarGit",
>         "Sublime Bookmarks",
>         "SublimeLinter",
>         "SublimeLinter-contrib-scss-lint",
>         "SublimeLinter-csslint",
>         "SublimeLinter-html-tidy",
>         "SublimeLinter-jshint",
>         "TabsExtra",
>         "Terminal",
>         "tern_for_sublime",
>         "Theme - Phoenix",
>         "WakaTime",
>         "WordCount",
>         "WordHighlight",
>         "WordPress"
>     ],

Colorscheme: https://packagecontrol.io/packages/Theme%20-%20Phoenix
Theme: https://packagecontrol.io/packages/Monokai%20Extended
Syntax: https://packagecontrol.io/packages/SCSS

The square below cursor is displayed always (even if it is a blank line)
When I disable PxRemTooltop, the square doesn't exist

**Comment by tbremer** [comment]
Okay, I see it now. My theme was hiding it.

Thanks! I'll look at this one tonight as well.
